name = "sql"
version = "0.1.0"
formatter = "core/sql/main.rhai"

# Grammar source: https://github.com/m-novikov/tree-sitter-sql
# Grammar tag: none
# Grammar commit: 587f30d

extensions = [".sql"]

[treesitter]
language = "sql"
binary = "core/treesitter/{os}/{arch}/sql.{ext}"
