name = "json"
version = "0.1.0"
formatter = "core/json/main.rhai"

# Grammar source: https://github.com/tree-sitter/tree-sitter-json
# Grammar tag: none
# Grammar commit: 001c28d

extensions = [".json"]

[treesitter]
language = "json"
binary = "core/treesitter/{os}/{arch}/json.{ext}"
