name = "html"
version = "0.1.0"
formatter = "core/html/main.rhai"
# Grammar source: https://github.com/tree-sitter/tree-sitter-html
# Grammar tag: none
# Grammar commit: 73a3947
fragment-marker = "<!-- {marker} -->"

extensions = [".html", ".htm"]

[treesitter]
language = "html"
binary = "core/treesitter/{os}/{arch}/html.{ext}"
